-- Cria a tabela BOARDS
CREATE TABLE IF NOT EXISTS BOARDS(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
    ) ENGINE=InnoDB;

-- Cria a tabela de colunas dos quadros
CREATE TABLE IF NOT EXISTS BOARDS_COLUMNS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kind VARCHAR(50) NOT NULL,
    `order` INT NOT NULL,
    board_id BIGINT NOT NULL,

    CONSTRAINT FK_COLUMNS_ON_BOARD
    FOREIGN KEY (board_id) REFERENCES BOARDS(id) ON DELETE CASCADE,

    CONSTRAINT UK_BOARD_ORDER
    UNIQUE KEY (board_id, `order`)
    ) ENGINE=InnoDB;


-- Cria a tabela de cartões (Cards)
CREATE TABLE IF NOT EXISTS CARDS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    board_column_id BIGINT NOT NULL,

    CONSTRAINT FK_CARDS_ON_COLUMN
    FOREIGN KEY (board_column_id) REFERENCES BOARDS_COLUMNS(id) ON DELETE CASCADE
    ) ENGINE=InnoDB;



-- Criar a tabela de bloqueados(Blocks)
CREATE TABLE IF NOT EXISTS BLOCKS (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      card_id BIGINT NOT NULL,
      block_cause TEXT NOT NULL,
      unblock_cause TEXT NULL,
      block_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      unblock_timestamp TIMESTAMP NULL,

      CONSTRAINT FK_BLOCKS_ON_CARD
      FOREIGN KEY (card_id) REFERENCES CARDS(id) ON DELETE CASCADE
    ) ENGINE=InnoDB;


--Criar a tabela Card_movement_History
CREATE TABLE IF NOT EXISTS CARD_MOVEMENT_HISTORY (
      id BIGINT AUTO_INCREMENT PRIMARY KEY,
      card_id BIGINT NOT NULL,
      from_column_id BIGINT NULL,
      to_column_id BIGINT NULL, -- CORREÇÃO: Removido o NOT NULL para permitir a ação ON DELETE SET NULL

      movement_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT FK_MOVEMENT_ON_CARD
      FOREIGN KEY (card_id) REFERENCES CARDS(id) ON DELETE CASCADE,

    CONSTRAINT FK_MOVEMENT_FROM_COLUMN
    FOREIGN KEY (from_column_id) REFERENCES BOARDS_COLUMNS(id) ON DELETE SET NULL,

    CONSTRAINT FK_MOVEMENT_TO_COLUMN
    FOREIGN KEY (to_column_id) REFERENCES BOARDS_COLUMNS(id) ON DELETE SET NULL
    ) ENGINE=InnoDB;
